name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH config
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Copy project files to VPS
        run: |
          rsync -avz \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="dist" \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/portfolio/

      - name: Build Portfolio on VPS
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " \
            cd /var/www/portfolio && \
            docker compose run --rm portafolio bun run build \
          "

      - name: Copy /dist to Nginx folder
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " \
            rm -rf /var/www/portfolio/dist && \
            cp -r /var/www/portfolio/dist /var/www/portfolio/dist \
          "

      - name: Reload Nginx
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl reload nginx"
